/*
 * File: app/controller/Canvas.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Canvas', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            toolPen: '#ToolPen',
            toolEraser: '#ToolEraser',
            roomNum: '#RoomNum',
            toolNew: '#ToolNew',
            toolSetting: '#ToolSetting',
            colorRed: '#ColorRed',
            colorBlue: '#ColorBlue',
            colorYellow: '#ColorYellow',
            colorGreen: '#ColorGreen',
            colorBlack: '#ColorBlack',
            colorGray: '#ColorGray',
            canvasView: '#CanvasView',
            topToolbar: '#TopToolbar',
            bottomToolbar: '#BottomToolbar'
        },

        control: {
            "toolPen": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, options) {
        
    }

});