/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */


// global variable
 
var strokeStyle = 'black';			// line color
var fillStyle = 'white';			// fill color
var lineWidth = 1;					// line width
var isDraw = false;					// draw status
var mode = 'pen';					// pen mode
var newPoint, oldPoint;

// point class
Ext.define('Point', {
    config: {
        x: null,
        y: null,
        width: null,
        color: null,
    },
 
    constructor: function(config) {
        this.initConfig(config);
    }
});

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    views: [
        'Draw'
    ],
    name: 'MyApp',
    controllers: [
        'Canvas',
        'Main'
    ],

    launch: function() {

        Ext.create('MyApp.view.Draw', {fullscreen: true});
    }

});
