/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: '#MainView',
            makeRoom: '#MakeRoom',
            connect: '#Connect',
            main: '#Main'
        },

        control: {
            "[action=Room]": {
                tap: 'onButtonTapMakeRoom'
            },
            "[action=connection]": {
                tap: 'onButtonTapConnect'
            }
        }
    },

    onButtonTapMakeRoom: function(button, e, options) {
        console.log('button makeroom tap');

        this.getMain().animateActiveItem(1, {type: 'reveal', direction: 'up'});
    },

    onButtonTapConnect: function(button, e, options) {
        console.log('button connect tap');

        Ext.Msg.show({
            title   : '방번호를 입력하세요',
            msg     : null,
            buttons : [{
                itemId : 'ok',
                text   : '참여하기',
                ui     : 'action'
            },{
                itemId : 'cancle',
                text   : '취소'
            }],
            prompt  : { maxlength : 6, autocapitalize : false },
            fn      : function(text,val) {
                // do some stuff
                console.log(text);
                console.log(val);

                if(text == 'ok') {
                    Ext.getCmp('RoomNum').setText(val);
                    Ext.getCmp('Main').animateActiveItem(1, {type: 'reveal', direction: 'down'});
                } else {

                }
            }
        });
    }

});